### ISSUE TITLE
In some cases the plugin blocks other plugins for the leader 

### ISSUE THREAD

**Issue by 13413j1j13j5315n13** [13413j1j13j5315n13/FollowerV2#17]
From the forum message:
> I found one issue: if leader has plugin turned on and functionality on but the follower functionality is turned off, the plugin blocks other plugins for the leader (FlaskRoutine, IconsBuilder)

**Comment by IlliumIv** [comment]
Maybe it have same solution with https://github.com/13413j1j13j5315n13/FollowerV2/issues/18

**Comment by 13413j1j13j5315n13** [comment]
Closing for now. Reopen if relevant
