### ISSUE TITLE
Pickit plugin on the leader side is "half the speed"

### ISSUE THREAD

**Issue by 13413j1j13j5315n13** [13413j1j13j5315n13/FollowerV2#18]
From the forum:
> the plugin stashie and pickit are working more slowly if the follower plugin ist enabled. i have tested it on the leader site, it seems to be half the speed if the follower plugin is enabled.

**Comment by IlliumIv** [comment]
Problem is in Server.Listen() method.
I solved it by make request async: https://github.com/IlliumIv/FollowerV2/blob/master/Server.cs

**Comment by 13413j1j13j5315n13** [comment]
@IlliumIv could you please check once again? I think amount of "actions" for coroutines was limited. Now both the server and network requesting functionalities are in normal separate threads. So all other coroutines (=plugins) should work normally.

**Comment by 13413j1j13j5315n13** [comment]
Closing for now. Reopen if relevant
